[build]
beforeDevCommand = "trunk serve"
beforeBuildCommand = "trunk build"
devPath = "http://localhost:1420"
distDir = "../dist"
withGlobalTauri = true

[package]
productName = "Basic Calculator"
version = "0.0.0"

[tauri.allowlist]
all = false

  [tauri.allowlist.shell]
  all = false
  open = true

[[tauri.windows]]
fullscreen = false
resizable = true
title = "Basic Calculator"
width = 600
height = 600

[tauri.security]

[tauri.bundle]
active = true
targets = "all"
identifier = "com.RexielScarlet.dev"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
